#!/bin/bash

obsvrNetwork=ch-obsvr
clientNetwork=ch-client

function getToDaChoppa() {
  echo
cat << "EOF"
                                         /\
                                        /  \
               -----------!----------- /    \
----------!----------  /=====\        /  /\  \
        |===\_________/__o___|   /\  /  /  \  \
       /_]    o o o o  ___  /   /  \/  /    \  \
\/\   <_]__[]_________<___>/   /    \ /      \  \
/  \      o             o     /      \        \  \
...................................................
EOF
  echo
  echo -e "\033[1;32mChinook - Get to the Choppa! \033[0m"
  echo
}

# client --------------------------------------------------------

function createClientNetwork() {
  if [[ $(docker network ls | grep -w $clientNetwork) ]]; then
    echo "${clientNetwork} network already exits."
    echo ""
  else
    echo -e "\033[1;32mChinook - Setting up $clientNetwork network... \033[0m"
    docker network create $clientNetwork \
      --attachable \
      -d bridge \
      --subnet 172.18.0.0/24 || true
    echo
  fi
}

function createDockerRegistry() {
  echo -e "\033[1;32mChinook - Creating docker registry... \033[0m"
  docker compose -v -f ./docker/docker-compose-regi.yml up -d --remove-orphans
  echo
}

function destroyDockerRegistry() {
  echo -e "\033[1;32mChinook - Destroying docker registry... \033[0m"
  docker rm -f ch-regi
  echo
}

function createClientImages() {
  echo -e "\033[1;32mChinook - Building and deploy images to docker registry... \033[0m"
  make -C ./docker/ch-base docker-build
  make -C ./apps/api docker-build
  make -C ./apps/db docker-build
  echo
}

function createClientContainers() {
  echo -e "\033[1;32mChinook - Composing web containers... \033[0m"
  docker compose -f ./docker/docker-compose-web.yml up -d --remove-orphans
  echo 
}

function seedClient() {
  echo -e "\033[1;32mChinook - Seeding database... \033[0m"
  make -C ./apps/db docker-seed
  echo
}

function destroyClientContainers() {
  echo -e "\033[1;32mChinook - Stopping and removing client containers... \033[0m"
  docker rm -f ch-api-web ch-db-pg
  echo
}

function destroyClientImages() {
  echo -e "\033[1;32mChinook - Removing images... \033[0m"
  docker rmi localhost:5000/ch/base:latest localhost:5000/ch/api-web:latest localhost:5000/ch/db-pg:latest
  echo
}

function destroyClientNetwork() {
  echo -e "\033[1;32mChinook - Destroying client network $clientNetwork \033[0m"
  docker network rm $clientNetwork
  echo
}

# obsvr --------------------------------------------------------

function createObsvrNetwork() {
  echo -e "\033[1;32mChinook - Setting up $obsvrNetwork network... \033[0m"
  docker network create $obsvrNetwork \
    --attachable \
    -d bridge \
    --subnet 172.18.1.0/24 || true
  echo 
}

function createObsvrContainers() {
  echo -e "\033[1;32mChinook - Composing Obsvr containers... \033[0m"
  docker compose -f ./docker/docker-compose-obsvr.yml up -d --remove-orphans
  echo
}

function destroyObsvrImages() {
  echo -e "\033[1;32mChinook - Removing images... \033[0m"
  docker rmi grafana/grafana:latest grafana/loki:latest prom/prometheus:latest
  echo
}

function destroyObsvrContainers() {
  echo -e "\033[1;32mChinook - Stopping and removing obsvr containers... \033[0m"
  docker rm -f -v ch-graf ch-loki ch-prom
  echo
}

function destroyObsvrNetwork() {
  echo -e "\033[1;32mChinook - Destroying obsvr network $obsvrNetwork... \033[0m"
  docker network rm $obsvrNetwork
  echo
}

# case handlers --------------------------------------------------------

function createClient() {
  destroyClientContainers
  destroyClientImages

  createClientImages
  createClientContainers
  seedClient
}

function createObsvr() {
  destroyObsvrContainers
  destroyObsvrNetwork
  
  createObsvrNetwork
  createObsvrContainers
}

function destroyAll() {
  destroyObsvrContainers
  destroyObsvrNetwork
  destroyDockerRegistry
  destroyClientContainers
  destroyClientImages
  destroyClientNetwork
}

# handle init --------------------------------------------------------

args=("destroy client obsvr regi")
error_message="\033[1;31mChinook - Argument of < ${args} > is required! \033[0m"

# vaidate argument
if [[ ! $(echo ${args[@]} | fgrep -w $1) ]]; then
    echo -e ${error_message}
    exit 1
fi

getToDaChoppa

if [[ ! $1 == 'destroy' ]]; then
  createClientNetwork
fi

case "$1" in
  destroy)
    destroyAll
    ;;
  client)
    createClient
    ;;
  obsvr)
    createObsvr
    ;;
  regi)
    destroyDockerRegistry
    createDockerRegistry
    ;;
  *)
    echo -e "${error_message}"
    exit 1
esac