#!/bin/bash

function get_to_the_choppa() {
  echo
cat << "EOF"
                                         /\
                                        /  \
               -----------!----------- /    \
----------!----------  /=====\        /  /\  \
        |===\_________/__o___|   /\  /  /  \  \
       /_]    o o o o  ___  /   /  \/  /    \  \
\/\   <_]__[]_________<___>/   /    \ /      \  \
/  \      o             o     /      \        \  \
...................................................
EOF
  echo
  echo -e "\033[1;32mChinook - Get to the Choppa! \033[0m"
  echo
}

function handle_status() {
  docker ps
  echo ""
}

function handle() {
  filename=$1
  if [[ "$2" == "restart" ]]; then
      docker-compose -f docker-compose-${filename}.yml down $3
      docker-compose -f docker-compose-${filename}.yml up -d $3
  elif [[ "$2" == "up" ]]; then
    docker-compose -f docker-compose-${filename}.yml up -d $3
  elif [[ "$2" == "down" ]]; then  
    docker-compose -f docker-compose-${filename}.yml down $3
  fi
}

get_to_the_choppa

case "$1" in
  client)
    handle "$@"
    ;;
  obsvr)
    handle "$@"
    ;;
  status)
    handle_status
    ;;
  *)
    echo "Invalid option"
    echo -e "${error_message}"
    exit 1
esac
