name: ch

services:
  db-pg:
    extends:
      file: ./apps/db/docker-compose.yml
      service: db-pg
    ports:
      - '5432:5432'
    networks:
      - backend

  api-web:
    extends:
      file: ./apps/api/docker-compose.yml
      service: api-web
    ports:
      - '8000:8000'
      - '9090:9090'
    networks:
      - backend
    depends_on:
      db-pg:
        condition: service_healthy

  prometheus:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-prometheus
    ports:
      - 9090:9090
    networks:
      - backend

  grafana:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-grafana
    ports:
      - '3000:3000'
    networks:
      - backend

networks:
  backend:
    driver: bridge
