name: ch

networks:
  ch-client-network:
    external: true
  ch-obsvr-network:
    external: true

services:
  alloy:
    build: ./obsvr/alloy
    hostname: ch-alloy
    networks: [ch-client-network, ch-obsvr-network]
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental  --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "4319:4317"
    environment:
      - ALLOY_OTLP_UPSTREAM=ch-tempo-1:4317
    volumes:
      - ./obsvr/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./_data/alloy-data:/var/lib/alloy/data
      - ./_logs/pg-logs:/var/log/postgresql:ro
      - ./_logs/api-logs:/var/log/ch-client-api:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:12345/-/ready"]
      interval: 10s
      timeout: 5s

  grafana:
    image: grafana/grafana:11.4.0
    hostname: ch-grafana
    networks: [ch-obsvr-network]
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
    volumes:
      - ./_data/grafana-data:/var/lib/grafana
      - ./obsvr/grafana/provisioning:/etc/grafana/provisioning/datasources:ro
      - ./obsvr/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      loki:
        condition: service_healthy
      # tempo:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  loki:
    image: grafana/loki:3.3.2
    hostname: ch-loki
    networks: [ch-obsvr-network]
    ports:
      - "3100:3100"
    volumes:
      - ./_data/loki-data:/loki
      - ./obsvr/loki/config.yaml:/etc/loki/config.yaml:ro
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  tempo:
    image: grafana/tempo:2.7.1
    hostname: ch-tempo
    networks: [ch-obsvr-network]
    command: -config.file=/etc/tempo/config.yaml
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ch-alloy-1:4318
    volumes:
      - ./_data/tempo-data:/var/tempo
      - ./obsvr/tempo/config.yaml:/etc/tempo/config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    hostname: ch-prometheus
    restart: unless-stopped
    networks: [ch-client-network, ch-obsvr-network]
    ports:
      - "9090:9090"
    volumes:
      - ./obsvr/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./_data/prometheus-data:/prometheus
