name: ch

networks:
  ch-client-network:
    name: ch-client-network
  ch-obsvr-network:
    name: ch-obsvr-network

services:
  client-db:
    image: postgres:18
    hostname: ch-client-db
    container_name: ch-client-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.50"
          memory: 128M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chinook
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgresql.log
    ports:
      - "5432:5432"
    volumes:
      - ./_data/pg-data:/var/lib/postgresql
      - ./_logs/pg-logs:/var/log/postgresql
    networks:
      - ch-client-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d chinook'"]
      interval: 3s
      timeout: 3s
      retries: 30

  client-db-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    hostname: ch-client-db-exporter
    networks: [ch-client-network, ch-obsvr-network]
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 64M
    command:
      - "--no-collector.stat_bgwriter"
    environment:
      PG_COLLECTOR_DATABASE_ENABLED: false
      PG_COLLECTOR_REPLICATION_ENABLED: false
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@ch-client-db:5432/chinook?sslmode=disable"
    ports:
      - "9187:9187"
    volumes:
      - ./obsvr/postgres_exporter/postgres_exporter.yml:/postgres_exporter.yml
    depends_on:
      client-db:
        condition: service_healthy

  client-api:
    build: ./apps/api
    hostname: ch-client-api
    container_name: ch-client-api
    working_dir: /var/www/app
    restart: unless-stopped
    command: make start
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.50"
          memory: 128M
    environment:
      GO_ENV: development
    ports:
      - 8000:8000
      - 9092:9092
    volumes:
      - ./apps/api/bin:/var/www/app
      - ./_logs/ch-client-api:/var/log/ch-client-api
    networks:
      - ch-client-network
    depends_on:
      client-db:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "sh -c 'curl -k https://localhost:8000/api/v1/health'"]
      interval: 30s
      timeout: 3s
      retries: 30
