name: ch

services:
  db-pg:
    extends:
      file: ./apps/db/docker-compose.yml
      service: db-pg
    expose:
      - 5432
    networks:
      backend:
        ipv4_address: 172.18.0.2

  api-web:
    build: ./apps/api
    extends:
      file: ./apps/api/docker-compose.yml
      service: api-web
    ports:
      - 8000:8000
      - 9100:9100
      - 127.0.0.1:80:80
    networks:
      backend:
        ipv4_address: 172.18.0.3
    depends_on:
      db-pg:
        condition: service_healthy

  obsvr-prom:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-prom
    ports:
      - 9090:9090
    networks:
      backend:
        ipv4_address: 172.18.0.4

  obsvr-graf:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-graf
    ports:
      - 3000:3000
    networks:
      backend:
        ipv4_address: 172.18.0.5

  obsvr-loki:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-loki
    ports:
      - 3100:3100
    networks:
      backend:
        ipv4_address: 172.18.0.6

  obsvr-alloy:
    extends:
      file: ./apps/obsvr/docker-compose.yml
      service: obsvr-alloy
    ports:
      - 12345:12345
    networks:
      backend:
        ipv4_address: 172.18.0.7

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
