name: ch
services:
  db-pg:
    build: .
    restart: always
    expose:
      - 5432
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./pg-data:/var/lib/postgresql
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U admin -d chinook'"]
      interval: 3s
      timeout: 3s
      retries: 30

volumes:
  pg-data:
