name: ch
services:
  db-pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chinook
    volumes:
      - ./pg-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U admin -d chinook'"]
      interval: 3s
      timeout: 3s
      retries: 30

volumes:
  pg-data:
