name: ch

services:

  regi:
    image: registry:3
    container_name: ch-regi
    ports:
      - 5000:5000
    networks:
      - shared-ch-client-network

networks:
  shared-ch-client-network:
    external: true
    name: ch-client-network