name: ch

services:
  client-db:
    image: localhost:5000/ch/client-db:latest
    container_name: ch-client-db
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 9100
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    networks:
      - shared-ch-client-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d chinook'"]
      interval: 3s
      timeout: 3s
      retries: 30

  client-api:
    image: localhost:5000/ch/client-api:latest
    container_name: ch-client-api
    restart: unless-stopped
    ports:
      - 8000:8000
    expose:
      - 9100
    networks:
      - shared-ch-client-network
    depends_on:
      client-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'curl -k https://localhost:8000/api/v1/health'"]
      interval: 30s
      timeout: 3s
      retries: 30

networks:
  shared-ch-client-network:
    external: true
    name: ch-client-network

volumes:
  pg-data:
